INSERT INTO moderation_rules (rule_id, rule_name, rule_type, rule_pattern, threshold, action, risk_category, enabled, priority)
SELECT * FROM (VALUES
    ('rule-008', '毒性内容检测', 'KEYWORD', '毒性|有毒|中毒|toxic|poison', 0.8, 'REVIEW', '毒性', TRUE, 20),
    ('rule-009', '侮辱内容检测', 'KEYWORD', '侮辱|辱骂|骂人|insult|abusive|humiliate', 0.8, 'REVIEW', '侮辱', TRUE, 20),
    ('rule-010', '亵渎内容检测', 'KEYWORD', '亵渎|脏话|粗口|profanity|swear|obscene', 0.8, 'REVIEW', '亵渎', TRUE, 20),
    ('rule-011', '贬损内容检测', 'KEYWORD', '贬损|贬低|诋毁|derogatory|belittle|defame', 0.8, 'REVIEW', '贬损', TRUE, 20),
    ('rule-012', '死亡伤害与悲剧检测', 'KEYWORD', '死亡|自杀|伤害|悲剧|death|suicide|tragedy|self-harm', 0.8, 'REVIEW', '死亡伤害与悲剧', TRUE, 15),
    ('rule-013', '枪支与武器检测', 'KEYWORD', '枪支|武器|枪械|弹药|firearm|weapon|gun|ammunition', 0.8, 'REVIEW', '枪支与武器', TRUE, 20),
    ('rule-014', '公共安全检测', 'KEYWORD', '公共安全|安全事故|爆炸|纵火|public safety|explosion|arson', 0.8, 'REVIEW', '公共安全', TRUE, 20),
    ('rule-015', '健康内容检测', 'KEYWORD', '健康|疾病|医疗|药品|health|disease|medical|medicine', 0.7, 'REVIEW', '健康', TRUE, 20),
    ('rule-016', '宗教与信仰检测', 'KEYWORD', '宗教|信仰|邪教|religion|belief|cult|faith', 0.8, 'REVIEW', '宗教与信仰', TRUE, 15),
    ('rule-017', '非法药物检测', 'KEYWORD', '毒品|药物滥用|吸毒|drug|narcotic|cocaine|heroin|meth', 0.8, 'REVIEW', '非法药物', TRUE, 20),
    ('rule-018', '战争与冲突检测', 'KEYWORD', '战争|冲突|军事|袭击|war|conflict|military|attack', 0.8, 'REVIEW', '战争与冲突', TRUE, 15),
    ('rule-019', '金融内容检测', 'KEYWORD', '金融|投资|理财|股票|证券|finance|investment|stock|securities', 0.7, 'REVIEW', '金融', TRUE, 20),
    ('rule-020', '法律内容检测', 'KEYWORD', '法律|违法|犯罪|诉讼|legal|illegal|crime|lawsuit', 0.7, 'REVIEW', '法律', TRUE, 20),
    ('rule-021', '涉密内容检测', 'KEYWORD', '国家秘密|机密|绝密|机密文件|泄露|classified|state secret|top secret', 0.9, 'BLOCK', '涉密', TRUE, 5),
    ('rule-022', '涉军内容检测', 'KEYWORD', '军队|军事基地|军事设施|国防|部队|军工|military base|defense|armed forces', 0.8, 'REVIEW', '涉军', TRUE, 10),
    ('rule-023', '涉政内容检测', 'KEYWORD', '政府|政权|执政|体制|颠覆|regime|government|ruling|overthrow', 0.8, 'REVIEW', '涉政', TRUE, 20),
    ('rule-024', '涉领导人检测', 'KEYWORD', '领导人|主席|总书记|总理|国家主席|president|chairman|premier|head of state', 0.9, 'BLOCK', '涉领导人', TRUE, 5),
    ('rule-025', '恐怖主义检测', 'KEYWORD', '恐怖主义|恐怖袭击|恐怖分子|terrorism|terrorist|terror attack|jihad', 0.9, 'BLOCK', '恐怖主义', TRUE, 5),
    ('rule-026', '赌博内容检测', 'KEYWORD', '赌博|赌场|博彩|赌球|赌钱|gambling|casino|betting|wager', 0.8, 'REVIEW', '赌博', TRUE, 20),
    ('rule-027', '欺诈诈骗检测', 'KEYWORD', '诈骗|欺诈|骗局|钓鱼|套取|fraud|scam|phishing|deceive', 0.8, 'REVIEW', '欺诈', TRUE, 20),
    ('rule-028', '谣言虚假信息检测', 'KEYWORD', '谣言|虚假信息|造谣|传谣|misinformation|rumor|fake news|disinformation', 0.8, 'REVIEW', '谣言', TRUE, 20),
    ('rule-029', '分裂主义检测', 'KEYWORD', '分裂|独立|分裂主义|分裂国家|separatism|secession|independence', 0.9, 'BLOCK', '分裂主义', TRUE, 5),
    ('rule-030', '极端主义检测', 'KEYWORD', '极端主义|极端思想|极端组织|extremism|extremist|radical|fundamentalist', 0.9, 'BLOCK', '极端主义', TRUE, 5),
    ('rule-031', '网络暴力检测', 'KEYWORD', '网络暴力|霸凌|网暴|人身攻击|cyberbullying|online harassment|doxxing', 0.8, 'REVIEW', '网络暴力', TRUE, 20),
    ('rule-032', '低俗内容检测', 'KEYWORD', '低俗|媚俗|恶俗|擦边|vulgar|indecent|tasteless|sleazy', 0.7, 'REVIEW', '低俗', TRUE, 20),
    ('rule-033', '侵犯知识产权检测', 'KEYWORD', '盗版|侵权|破解|版权|piracy|copyright|infringement|crack', 0.8, 'REVIEW', '侵犯知识产权', TRUE, 20),
    ('rule-034', '非法集资传销检测', 'KEYWORD', '传销|非法集资|金字塔|庞氏|pyramid scheme|ponzi|illegal fundraising', 0.8, 'REVIEW', '非法集资传销', TRUE, 20),
    ('rule-035', '危害网络安全检测', 'KEYWORD', '黑客|攻击|病毒|漏洞|木马|hacking|virus|exploit|malware|trojan', 0.8, 'REVIEW', '危害网络安全', TRUE, 20),
    ('rule-036', '非法社会组织检测', 'KEYWORD', '非法组织|地下组织|非法社团|illegal organization|underground group', 0.8, 'REVIEW', '非法社会组织', TRUE, 20),
    ('rule-037', '历史虚无主义检测', 'KEYWORD', '历史虚无主义|歪曲历史|否定历史|historical nihilism|distort history', 0.9, 'BLOCK', '历史虚无主义', TRUE, 10),
    ('rule-038', '性别歧视物化检测', 'KEYWORD', '性别歧视|物化女性|物化|gender discrimination|objectification|sexism', 0.8, 'REVIEW', '性别歧视物化', TRUE, 20),
    ('rule-039', '邪教内容检测', 'KEYWORD', '邪教|邪教组织|邪教教主|cult|cult leader|evil cult', 0.9, 'BLOCK', '邪教', TRUE, 5)
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM moderation_rules WHERE moderation_rules.rule_id = tmp.column1);