// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// LocalID applies equality check predicate on the "local_id" field. It's identical to LocalIDEQ.
func LocalID(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldLocalID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// PublicModel applies equality check predicate on the "public_model" field. It's identical to PublicModelEQ.
func PublicModel(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldPublicModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAccountID, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldStatus, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResolution, v))
}

// DurationSec applies equality check predicate on the "duration_sec" field. It's identical to DurationSecEQ.
func DurationSec(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldDurationSec, v))
}

// VideoURL applies equality check predicate on the "video_url" field. It's identical to VideoURLEQ.
func VideoURL(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldVideoURL, v))
}

// ThumbnailURL applies equality check predicate on the "thumbnail_url" field. It's identical to ThumbnailURLEQ.
func ThumbnailURL(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldThumbnailURL, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldErrorMessage, v))
}

// CostUsd applies equality check predicate on the "cost_usd" field. It's identical to CostUsdEQ.
func CostUsd(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCostUsd, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// LocalIDEQ applies the EQ predicate on the "local_id" field.
func LocalIDEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldLocalID, v))
}

// LocalIDNEQ applies the NEQ predicate on the "local_id" field.
func LocalIDNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldLocalID, v))
}

// LocalIDIn applies the In predicate on the "local_id" field.
func LocalIDIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldLocalID, vs...))
}

// LocalIDNotIn applies the NotIn predicate on the "local_id" field.
func LocalIDNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldLocalID, vs...))
}

// LocalIDGT applies the GT predicate on the "local_id" field.
func LocalIDGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldLocalID, v))
}

// LocalIDGTE applies the GTE predicate on the "local_id" field.
func LocalIDGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldLocalID, v))
}

// LocalIDLT applies the LT predicate on the "local_id" field.
func LocalIDLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldLocalID, v))
}

// LocalIDLTE applies the LTE predicate on the "local_id" field.
func LocalIDLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldLocalID, v))
}

// LocalIDContains applies the Contains predicate on the "local_id" field.
func LocalIDContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldLocalID, v))
}

// LocalIDHasPrefix applies the HasPrefix predicate on the "local_id" field.
func LocalIDHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldLocalID, v))
}

// LocalIDHasSuffix applies the HasSuffix predicate on the "local_id" field.
func LocalIDHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldLocalID, v))
}

// LocalIDEqualFold applies the EqualFold predicate on the "local_id" field.
func LocalIDEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldLocalID, v))
}

// LocalIDContainsFold applies the ContainsFold predicate on the "local_id" field.
func LocalIDContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldLocalID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldAPIKeyID))
}

// PublicModelEQ applies the EQ predicate on the "public_model" field.
func PublicModelEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldPublicModel, v))
}

// PublicModelNEQ applies the NEQ predicate on the "public_model" field.
func PublicModelNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldPublicModel, v))
}

// PublicModelIn applies the In predicate on the "public_model" field.
func PublicModelIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldPublicModel, vs...))
}

// PublicModelNotIn applies the NotIn predicate on the "public_model" field.
func PublicModelNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldPublicModel, vs...))
}

// PublicModelGT applies the GT predicate on the "public_model" field.
func PublicModelGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldPublicModel, v))
}

// PublicModelGTE applies the GTE predicate on the "public_model" field.
func PublicModelGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldPublicModel, v))
}

// PublicModelLT applies the LT predicate on the "public_model" field.
func PublicModelLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldPublicModel, v))
}

// PublicModelLTE applies the LTE predicate on the "public_model" field.
func PublicModelLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldPublicModel, v))
}

// PublicModelContains applies the Contains predicate on the "public_model" field.
func PublicModelContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldPublicModel, v))
}

// PublicModelHasPrefix applies the HasPrefix predicate on the "public_model" field.
func PublicModelHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldPublicModel, v))
}

// PublicModelHasSuffix applies the HasSuffix predicate on the "public_model" field.
func PublicModelHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldPublicModel, v))
}

// PublicModelEqualFold applies the EqualFold predicate on the "public_model" field.
func PublicModelEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldPublicModel, v))
}

// PublicModelContainsFold applies the ContainsFold predicate on the "public_model" field.
func PublicModelContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldPublicModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldAccountID, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldStatus, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionIsNil applies the IsNil predicate on the "resolution" field.
func ResolutionIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldResolution))
}

// ResolutionNotNil applies the NotNil predicate on the "resolution" field.
func ResolutionNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldResolution))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldResolution, v))
}

// DurationSecEQ applies the EQ predicate on the "duration_sec" field.
func DurationSecEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldDurationSec, v))
}

// DurationSecNEQ applies the NEQ predicate on the "duration_sec" field.
func DurationSecNEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldDurationSec, v))
}

// DurationSecIn applies the In predicate on the "duration_sec" field.
func DurationSecIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldDurationSec, vs...))
}

// DurationSecNotIn applies the NotIn predicate on the "duration_sec" field.
func DurationSecNotIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldDurationSec, vs...))
}

// DurationSecGT applies the GT predicate on the "duration_sec" field.
func DurationSecGT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldDurationSec, v))
}

// DurationSecGTE applies the GTE predicate on the "duration_sec" field.
func DurationSecGTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldDurationSec, v))
}

// DurationSecLT applies the LT predicate on the "duration_sec" field.
func DurationSecLT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldDurationSec, v))
}

// DurationSecLTE applies the LTE predicate on the "duration_sec" field.
func DurationSecLTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldDurationSec, v))
}

// DurationSecIsNil applies the IsNil predicate on the "duration_sec" field.
func DurationSecIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldDurationSec))
}

// DurationSecNotNil applies the NotNil predicate on the "duration_sec" field.
func DurationSecNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldDurationSec))
}

// VideoURLEQ applies the EQ predicate on the "video_url" field.
func VideoURLEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldVideoURL, v))
}

// VideoURLNEQ applies the NEQ predicate on the "video_url" field.
func VideoURLNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldVideoURL, v))
}

// VideoURLIn applies the In predicate on the "video_url" field.
func VideoURLIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldVideoURL, vs...))
}

// VideoURLNotIn applies the NotIn predicate on the "video_url" field.
func VideoURLNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldVideoURL, vs...))
}

// VideoURLGT applies the GT predicate on the "video_url" field.
func VideoURLGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldVideoURL, v))
}

// VideoURLGTE applies the GTE predicate on the "video_url" field.
func VideoURLGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldVideoURL, v))
}

// VideoURLLT applies the LT predicate on the "video_url" field.
func VideoURLLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldVideoURL, v))
}

// VideoURLLTE applies the LTE predicate on the "video_url" field.
func VideoURLLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldVideoURL, v))
}

// VideoURLContains applies the Contains predicate on the "video_url" field.
func VideoURLContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldVideoURL, v))
}

// VideoURLHasPrefix applies the HasPrefix predicate on the "video_url" field.
func VideoURLHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldVideoURL, v))
}

// VideoURLHasSuffix applies the HasSuffix predicate on the "video_url" field.
func VideoURLHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldVideoURL, v))
}

// VideoURLIsNil applies the IsNil predicate on the "video_url" field.
func VideoURLIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldVideoURL))
}

// VideoURLNotNil applies the NotNil predicate on the "video_url" field.
func VideoURLNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldVideoURL))
}

// VideoURLEqualFold applies the EqualFold predicate on the "video_url" field.
func VideoURLEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldVideoURL, v))
}

// VideoURLContainsFold applies the ContainsFold predicate on the "video_url" field.
func VideoURLContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldVideoURL, v))
}

// ThumbnailURLEQ applies the EQ predicate on the "thumbnail_url" field.
func ThumbnailURLEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldThumbnailURL, v))
}

// ThumbnailURLNEQ applies the NEQ predicate on the "thumbnail_url" field.
func ThumbnailURLNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldThumbnailURL, v))
}

// ThumbnailURLIn applies the In predicate on the "thumbnail_url" field.
func ThumbnailURLIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldThumbnailURL, vs...))
}

// ThumbnailURLNotIn applies the NotIn predicate on the "thumbnail_url" field.
func ThumbnailURLNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldThumbnailURL, vs...))
}

// ThumbnailURLGT applies the GT predicate on the "thumbnail_url" field.
func ThumbnailURLGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldThumbnailURL, v))
}

// ThumbnailURLGTE applies the GTE predicate on the "thumbnail_url" field.
func ThumbnailURLGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldThumbnailURL, v))
}

// ThumbnailURLLT applies the LT predicate on the "thumbnail_url" field.
func ThumbnailURLLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldThumbnailURL, v))
}

// ThumbnailURLLTE applies the LTE predicate on the "thumbnail_url" field.
func ThumbnailURLLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldThumbnailURL, v))
}

// ThumbnailURLContains applies the Contains predicate on the "thumbnail_url" field.
func ThumbnailURLContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldThumbnailURL, v))
}

// ThumbnailURLHasPrefix applies the HasPrefix predicate on the "thumbnail_url" field.
func ThumbnailURLHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldThumbnailURL, v))
}

// ThumbnailURLHasSuffix applies the HasSuffix predicate on the "thumbnail_url" field.
func ThumbnailURLHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldThumbnailURL, v))
}

// ThumbnailURLIsNil applies the IsNil predicate on the "thumbnail_url" field.
func ThumbnailURLIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldThumbnailURL))
}

// ThumbnailURLNotNil applies the NotNil predicate on the "thumbnail_url" field.
func ThumbnailURLNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldThumbnailURL))
}

// ThumbnailURLEqualFold applies the EqualFold predicate on the "thumbnail_url" field.
func ThumbnailURLEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldThumbnailURL, v))
}

// ThumbnailURLContainsFold applies the ContainsFold predicate on the "thumbnail_url" field.
func ThumbnailURLContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldThumbnailURL, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldRequestBody))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CostUsdEQ applies the EQ predicate on the "cost_usd" field.
func CostUsdEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCostUsd, v))
}

// CostUsdNEQ applies the NEQ predicate on the "cost_usd" field.
func CostUsdNEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldCostUsd, v))
}

// CostUsdIn applies the In predicate on the "cost_usd" field.
func CostUsdIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldCostUsd, vs...))
}

// CostUsdNotIn applies the NotIn predicate on the "cost_usd" field.
func CostUsdNotIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldCostUsd, vs...))
}

// CostUsdGT applies the GT predicate on the "cost_usd" field.
func CostUsdGT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldCostUsd, v))
}

// CostUsdGTE applies the GTE predicate on the "cost_usd" field.
func CostUsdGTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldCostUsd, v))
}

// CostUsdLT applies the LT predicate on the "cost_usd" field.
func CostUsdLT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldCostUsd, v))
}

// CostUsdLTE applies the LTE predicate on the "cost_usd" field.
func CostUsdLTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldCostUsd, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.NotPredicates(p))
}
