// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/blog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BlogUpdate is the builder for updating Blog entities.
type BlogUpdate struct {
	config
	hooks    []Hook
	mutation *BlogMutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (_u *BlogUpdate) Where(ps ...predicate.Blog) *BlogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogUpdate) SetTitle(v string) *BlogUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableTitle(v *string) *BlogUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogUpdate) SetContent(v string) *BlogUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableContent(v *string) *BlogUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *BlogUpdate) SetSummary(v string) *BlogUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableSummary(v *string) *BlogUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *BlogUpdate) ClearSummary() *BlogUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *BlogUpdate) SetCoverImage(v string) *BlogUpdate {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableCoverImage(v *string) *BlogUpdate {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *BlogUpdate) ClearCoverImage() *BlogUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BlogUpdate) SetStatus(v string) *BlogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableStatus(v *string) *BlogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *BlogUpdate) SetTags(v string) *BlogUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableTags(v *string) *BlogUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *BlogUpdate) ClearTags() *BlogUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BlogUpdate) SetPublishedAt(v time.Time) *BlogUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BlogUpdate) SetNillablePublishedAt(v *time.Time) *BlogUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BlogUpdate) ClearPublishedAt() *BlogUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BlogUpdate) SetCreatedBy(v int64) *BlogUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableCreatedBy(v *int64) *BlogUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BlogUpdate) AddCreatedBy(v int64) *BlogUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BlogUpdate) ClearCreatedBy() *BlogUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogUpdate) SetUpdatedAt(v time.Time) *BlogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BlogUpdate) SetDeletedAt(v time.Time) *BlogUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableDeletedAt(v *time.Time) *BlogUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BlogUpdate) ClearDeletedAt() *BlogUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the BlogMutation object of the builder.
func (_u *BlogUpdate) Mutation() *BlogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := blog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Blog.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := blog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Blog.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := blog.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Blog.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := blog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Blog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BlogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(blog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(blog.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(blog.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(blog.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(blog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(blog.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(blog.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(blog.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(blog.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(blog.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(blog.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(blog.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(blog.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlogUpdateOne is the builder for updating a single Blog entity.
type BlogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogMutation
}

// SetTitle sets the "title" field.
func (_u *BlogUpdateOne) SetTitle(v string) *BlogUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableTitle(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogUpdateOne) SetContent(v string) *BlogUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableContent(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *BlogUpdateOne) SetSummary(v string) *BlogUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableSummary(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *BlogUpdateOne) ClearSummary() *BlogUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *BlogUpdateOne) SetCoverImage(v string) *BlogUpdateOne {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableCoverImage(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *BlogUpdateOne) ClearCoverImage() *BlogUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BlogUpdateOne) SetStatus(v string) *BlogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableStatus(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *BlogUpdateOne) SetTags(v string) *BlogUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableTags(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *BlogUpdateOne) ClearTags() *BlogUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BlogUpdateOne) SetPublishedAt(v time.Time) *BlogUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillablePublishedAt(v *time.Time) *BlogUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BlogUpdateOne) ClearPublishedAt() *BlogUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BlogUpdateOne) SetCreatedBy(v int64) *BlogUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableCreatedBy(v *int64) *BlogUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BlogUpdateOne) AddCreatedBy(v int64) *BlogUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BlogUpdateOne) ClearCreatedBy() *BlogUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogUpdateOne) SetUpdatedAt(v time.Time) *BlogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BlogUpdateOne) SetDeletedAt(v time.Time) *BlogUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableDeletedAt(v *time.Time) *BlogUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BlogUpdateOne) ClearDeletedAt() *BlogUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the BlogMutation object of the builder.
func (_u *BlogUpdateOne) Mutation() *BlogMutation {
	return _u.mutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (_u *BlogUpdateOne) Where(ps ...predicate.Blog) *BlogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlogUpdateOne) Select(field string, fields ...string) *BlogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Blog entity.
func (_u *BlogUpdateOne) Save(ctx context.Context) (*Blog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogUpdateOne) SaveX(ctx context.Context) *Blog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BlogUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := blog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Blog.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := blog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Blog.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := blog.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Blog.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := blog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Blog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BlogUpdateOne) sqlSave(ctx context.Context) (_node *Blog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blog.FieldID)
		for _, f := range fields {
			if !blog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(blog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(blog.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(blog.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(blog.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(blog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(blog.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(blog.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(blog.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(blog.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(blog.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(blog.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(blog.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(blog.FieldDeletedAt, field.TypeTime)
	}
	_node = &Blog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
