// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/blog"
)

// BlogCreate is the builder for creating a Blog entity.
type BlogCreate struct {
	config
	mutation *BlogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *BlogCreate) SetTitle(v string) *BlogCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *BlogCreate) SetContent(v string) *BlogCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *BlogCreate) SetSummary(v string) *BlogCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *BlogCreate) SetNillableSummary(v *string) *BlogCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetCoverImage sets the "cover_image" field.
func (_c *BlogCreate) SetCoverImage(v string) *BlogCreate {
	_c.mutation.SetCoverImage(v)
	return _c
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_c *BlogCreate) SetNillableCoverImage(v *string) *BlogCreate {
	if v != nil {
		_c.SetCoverImage(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BlogCreate) SetStatus(v string) *BlogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BlogCreate) SetNillableStatus(v *string) *BlogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *BlogCreate) SetTags(v string) *BlogCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *BlogCreate) SetNillableTags(v *string) *BlogCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *BlogCreate) SetPublishedAt(v time.Time) *BlogCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillablePublishedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *BlogCreate) SetCreatedBy(v int64) *BlogCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *BlogCreate) SetNillableCreatedBy(v *int64) *BlogCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogCreate) SetCreatedAt(v time.Time) *BlogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableCreatedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogCreate) SetUpdatedAt(v time.Time) *BlogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableUpdatedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BlogCreate) SetDeletedAt(v time.Time) *BlogCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableDeletedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// Mutation returns the BlogMutation object of the builder.
func (_c *BlogCreate) Mutation() *BlogMutation {
	return _c.mutation
}

// Save creates the Blog in the database.
func (_c *BlogCreate) Save(ctx context.Context) (*Blog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogCreate) SaveX(ctx context.Context) *Blog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogCreate) defaults() {
	if _, ok := _c.mutation.Summary(); !ok {
		v := blog.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.CoverImage(); !ok {
		v := blog.DefaultCoverImage
		_c.mutation.SetCoverImage(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := blog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := blog.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := blog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Blog.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Blog.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := blog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Blog.content": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := blog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Blog.summary": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverImage(); ok {
		if err := blog.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Blog.cover_image": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Blog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := blog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Blog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blog.updated_at"`)}
	}
	return nil
}

func (_c *BlogCreate) sqlSave(ctx context.Context) (*Blog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogCreate) createSpec() (*Blog, *sqlgraph.CreateSpec) {
	var (
		_node = &Blog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blog.Table, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(blog.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.CoverImage(); ok {
		_spec.SetField(blog.FieldCoverImage, field.TypeString, value)
		_node.CoverImage = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(blog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(blog.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(blog.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(blog.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blog.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlogUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *BlogCreate) OnConflict(opts ...sql.ConflictOption) *BlogUpsertOne {
	_c.conflict = opts
	return &BlogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BlogCreate) OnConflictColumns(columns ...string) *BlogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BlogUpsertOne{
		create: _c,
	}
}

type (
	// BlogUpsertOne is the builder for "upsert"-ing
	//  one Blog node.
	BlogUpsertOne struct {
		create *BlogCreate
	}

	// BlogUpsert is the "OnConflict" setter.
	BlogUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *BlogUpsert) SetTitle(v string) *BlogUpsert {
	u.Set(blog.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsert) UpdateTitle() *BlogUpsert {
	u.SetExcluded(blog.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *BlogUpsert) SetContent(v string) *BlogUpsert {
	u.Set(blog.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsert) UpdateContent() *BlogUpsert {
	u.SetExcluded(blog.FieldContent)
	return u
}

// SetSummary sets the "summary" field.
func (u *BlogUpsert) SetSummary(v string) *BlogUpsert {
	u.Set(blog.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *BlogUpsert) UpdateSummary() *BlogUpsert {
	u.SetExcluded(blog.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *BlogUpsert) ClearSummary() *BlogUpsert {
	u.SetNull(blog.FieldSummary)
	return u
}

// SetCoverImage sets the "cover_image" field.
func (u *BlogUpsert) SetCoverImage(v string) *BlogUpsert {
	u.Set(blog.FieldCoverImage, v)
	return u
}

// UpdateCoverImage sets the "cover_image" field to the value that was provided on create.
func (u *BlogUpsert) UpdateCoverImage() *BlogUpsert {
	u.SetExcluded(blog.FieldCoverImage)
	return u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (u *BlogUpsert) ClearCoverImage() *BlogUpsert {
	u.SetNull(blog.FieldCoverImage)
	return u
}

// SetStatus sets the "status" field.
func (u *BlogUpsert) SetStatus(v string) *BlogUpsert {
	u.Set(blog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BlogUpsert) UpdateStatus() *BlogUpsert {
	u.SetExcluded(blog.FieldStatus)
	return u
}

// SetTags sets the "tags" field.
func (u *BlogUpsert) SetTags(v string) *BlogUpsert {
	u.Set(blog.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsert) UpdateTags() *BlogUpsert {
	u.SetExcluded(blog.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *BlogUpsert) ClearTags() *BlogUpsert {
	u.SetNull(blog.FieldTags)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *BlogUpsert) SetPublishedAt(v time.Time) *BlogUpsert {
	u.Set(blog.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *BlogUpsert) UpdatePublishedAt() *BlogUpsert {
	u.SetExcluded(blog.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *BlogUpsert) ClearPublishedAt() *BlogUpsert {
	u.SetNull(blog.FieldPublishedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *BlogUpsert) SetCreatedBy(v int64) *BlogUpsert {
	u.Set(blog.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BlogUpsert) UpdateCreatedBy() *BlogUpsert {
	u.SetExcluded(blog.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BlogUpsert) AddCreatedBy(v int64) *BlogUpsert {
	u.Add(blog.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BlogUpsert) ClearCreatedBy() *BlogUpsert {
	u.SetNull(blog.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsert) SetUpdatedAt(v time.Time) *BlogUpsert {
	u.Set(blog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsert) UpdateUpdatedAt() *BlogUpsert {
	u.SetExcluded(blog.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsert) SetDeletedAt(v time.Time) *BlogUpsert {
	u.Set(blog.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsert) UpdateDeletedAt() *BlogUpsert {
	u.SetExcluded(blog.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BlogUpsert) ClearDeletedAt() *BlogUpsert {
	u.SetNull(blog.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BlogUpsertOne) UpdateNewValues() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(blog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BlogUpsertOne) Ignore() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlogUpsertOne) DoNothing() *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlogCreate.OnConflict
// documentation for more info.
func (u *BlogUpsertOne) Update(set func(*BlogUpsert)) *BlogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *BlogUpsertOne) SetTitle(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateTitle() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *BlogUpsertOne) SetContent(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateContent() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateContent()
	})
}

// SetSummary sets the "summary" field.
func (u *BlogUpsertOne) SetSummary(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateSummary() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *BlogUpsertOne) ClearSummary() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearSummary()
	})
}

// SetCoverImage sets the "cover_image" field.
func (u *BlogUpsertOne) SetCoverImage(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetCoverImage(v)
	})
}

// UpdateCoverImage sets the "cover_image" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateCoverImage() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCoverImage()
	})
}

// ClearCoverImage clears the value of the "cover_image" field.
func (u *BlogUpsertOne) ClearCoverImage() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearCoverImage()
	})
}

// SetStatus sets the "status" field.
func (u *BlogUpsertOne) SetStatus(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateStatus() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateStatus()
	})
}

// SetTags sets the "tags" field.
func (u *BlogUpsertOne) SetTags(v string) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateTags() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *BlogUpsertOne) ClearTags() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearTags()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *BlogUpsertOne) SetPublishedAt(v time.Time) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdatePublishedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *BlogUpsertOne) ClearPublishedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BlogUpsertOne) SetCreatedBy(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BlogUpsertOne) AddCreatedBy(v int64) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateCreatedBy() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BlogUpsertOne) ClearCreatedBy() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsertOne) SetUpdatedAt(v time.Time) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateUpdatedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsertOne) SetDeletedAt(v time.Time) *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsertOne) UpdateDeletedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BlogUpsertOne) ClearDeletedAt() *BlogUpsertOne {
	return u.Update(func(s *BlogUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *BlogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BlogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BlogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BlogCreateBulk is the builder for creating many Blog entities in bulk.
type BlogCreateBulk struct {
	config
	err      error
	builders []*BlogCreate
	conflict []sql.ConflictOption
}

// Save creates the Blog entities in the database.
func (_c *BlogCreateBulk) Save(ctx context.Context) ([]*Blog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Blog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogCreateBulk) SaveX(ctx context.Context) []*Blog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Blog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BlogUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *BlogCreateBulk) OnConflict(opts ...sql.ConflictOption) *BlogUpsertBulk {
	_c.conflict = opts
	return &BlogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BlogCreateBulk) OnConflictColumns(columns ...string) *BlogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BlogUpsertBulk{
		create: _c,
	}
}

// BlogUpsertBulk is the builder for "upsert"-ing
// a bulk of Blog nodes.
type BlogUpsertBulk struct {
	create *BlogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BlogUpsertBulk) UpdateNewValues() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(blog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Blog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BlogUpsertBulk) Ignore() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BlogUpsertBulk) DoNothing() *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BlogCreateBulk.OnConflict
// documentation for more info.
func (u *BlogUpsertBulk) Update(set func(*BlogUpsert)) *BlogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BlogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *BlogUpsertBulk) SetTitle(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateTitle() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *BlogUpsertBulk) SetContent(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateContent() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateContent()
	})
}

// SetSummary sets the "summary" field.
func (u *BlogUpsertBulk) SetSummary(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateSummary() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *BlogUpsertBulk) ClearSummary() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearSummary()
	})
}

// SetCoverImage sets the "cover_image" field.
func (u *BlogUpsertBulk) SetCoverImage(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetCoverImage(v)
	})
}

// UpdateCoverImage sets the "cover_image" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateCoverImage() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCoverImage()
	})
}

// ClearCoverImage clears the value of the "cover_image" field.
func (u *BlogUpsertBulk) ClearCoverImage() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearCoverImage()
	})
}

// SetStatus sets the "status" field.
func (u *BlogUpsertBulk) SetStatus(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateStatus() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateStatus()
	})
}

// SetTags sets the "tags" field.
func (u *BlogUpsertBulk) SetTags(v string) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateTags() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *BlogUpsertBulk) ClearTags() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearTags()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *BlogUpsertBulk) SetPublishedAt(v time.Time) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdatePublishedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *BlogUpsertBulk) ClearPublishedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BlogUpsertBulk) SetCreatedBy(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BlogUpsertBulk) AddCreatedBy(v int64) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateCreatedBy() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BlogUpsertBulk) ClearCreatedBy() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BlogUpsertBulk) SetUpdatedAt(v time.Time) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateUpdatedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BlogUpsertBulk) SetDeletedAt(v time.Time) *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BlogUpsertBulk) UpdateDeletedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BlogUpsertBulk) ClearDeletedAt() *BlogUpsertBulk {
	return u.Update(func(s *BlogUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *BlogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BlogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BlogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BlogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
