// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediatask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaTaskDelete is the builder for deleting a MediaTask entity.
type MediaTaskDelete struct {
	config
	hooks    []Hook
	mutation *MediaTaskMutation
}

// Where appends a list predicates to the MediaTaskDelete builder.
func (_d *MediaTaskDelete) Where(ps ...predicate.MediaTask) *MediaTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediatask.Table, sqlgraph.NewFieldSpec(mediatask.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaTaskDeleteOne is the builder for deleting a single MediaTask entity.
type MediaTaskDeleteOne struct {
	_d *MediaTaskDelete
}

// Where appends a list predicates to the MediaTaskDelete builder.
func (_d *MediaTaskDeleteOne) Where(ps ...predicate.MediaTask) *MediaTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediatask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
