// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamauditlog"
)

// TeamAuditLogCreate is the builder for creating a TeamAuditLog entity.
type TeamAuditLogCreate struct {
	config
	mutation *TeamAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTeamID sets the "team_id" field.
func (_c *TeamAuditLogCreate) SetTeamID(v int64) *TeamAuditLogCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamAuditLogCreate) SetUserID(v int64) *TeamAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableUserID(v *int64) *TeamAuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *TeamAuditLogCreate) SetAction(v string) *TeamAuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetOperationType sets the "operation_type" field.
func (_c *TeamAuditLogCreate) SetOperationType(v string) *TeamAuditLogCreate {
	_c.mutation.SetOperationType(v)
	return _c
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableOperationType(v *string) *TeamAuditLogCreate {
	if v != nil {
		_c.SetOperationType(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *TeamAuditLogCreate) SetResourceType(v string) *TeamAuditLogCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *TeamAuditLogCreate) SetResourceID(v int64) *TeamAuditLogCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableResourceID(v *int64) *TeamAuditLogCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetChanges sets the "changes" field.
func (_c *TeamAuditLogCreate) SetChanges(v map[string]interface{}) *TeamAuditLogCreate {
	_c.mutation.SetChanges(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *TeamAuditLogCreate) SetIP(v string) *TeamAuditLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableIP(v *string) *TeamAuditLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *TeamAuditLogCreate) SetUserAgent(v string) *TeamAuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableUserAgent(v *string) *TeamAuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamAuditLogCreate) SetCreatedAt(v time.Time) *TeamAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamAuditLogCreate) SetNillableCreatedAt(v *time.Time) *TeamAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamAuditLogCreate) SetTeam(v *Team) *TeamAuditLogCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamAuditLogMutation object of the builder.
func (_c *TeamAuditLogCreate) Mutation() *TeamAuditLogMutation {
	return _c.mutation
}

// Save creates the TeamAuditLog in the database.
func (_c *TeamAuditLogCreate) Save(ctx context.Context) (*TeamAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamAuditLogCreate) SaveX(ctx context.Context) *TeamAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamAuditLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamAuditLogCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamAuditLog.team_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "TeamAuditLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := teamauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperationType(); ok {
		if err := teamauditlog.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.operation_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "TeamAuditLog.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := teamauditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := teamauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamAuditLog.created_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamAuditLog.team"`)}
	}
	return nil
}

func (_c *TeamAuditLogCreate) sqlSave(ctx context.Context) (*TeamAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamAuditLogCreate) createSpec() (*TeamAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamauditlog.Table, sqlgraph.NewFieldSpec(teamauditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(teamauditlog.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(teamauditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.OperationType(); ok {
		_spec.SetField(teamauditlog.FieldOperationType, field.TypeString, value)
		_node.OperationType = &value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(teamauditlog.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(teamauditlog.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.Changes(); ok {
		_spec.SetField(teamauditlog.FieldChanges, field.TypeJSON, value)
		_node.Changes = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(teamauditlog.FieldIP, field.TypeString, value)
		_node.IP = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(teamauditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamauditlog.TeamTable,
			Columns: []string{teamauditlog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamAuditLog.Create().
//		SetTeamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamAuditLogUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *TeamAuditLogUpsertOne {
	_c.conflict = opts
	return &TeamAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamAuditLogCreate) OnConflictColumns(columns ...string) *TeamAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// TeamAuditLogUpsertOne is the builder for "upsert"-ing
	//  one TeamAuditLog node.
	TeamAuditLogUpsertOne struct {
		create *TeamAuditLogCreate
	}

	// TeamAuditLogUpsert is the "OnConflict" setter.
	TeamAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetTeamID sets the "team_id" field.
func (u *TeamAuditLogUpsert) SetTeamID(v int64) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateTeamID() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldTeamID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamAuditLogUpsert) SetUserID(v int64) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateUserID() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *TeamAuditLogUpsert) AddUserID(v int64) *TeamAuditLogUpsert {
	u.Add(teamauditlog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *TeamAuditLogUpsert) ClearUserID() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldUserID)
	return u
}

// SetAction sets the "action" field.
func (u *TeamAuditLogUpsert) SetAction(v string) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateAction() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldAction)
	return u
}

// SetOperationType sets the "operation_type" field.
func (u *TeamAuditLogUpsert) SetOperationType(v string) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldOperationType, v)
	return u
}

// UpdateOperationType sets the "operation_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateOperationType() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldOperationType)
	return u
}

// ClearOperationType clears the value of the "operation_type" field.
func (u *TeamAuditLogUpsert) ClearOperationType() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldOperationType)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *TeamAuditLogUpsert) SetResourceType(v string) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateResourceType() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *TeamAuditLogUpsert) SetResourceID(v int64) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateResourceID() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *TeamAuditLogUpsert) AddResourceID(v int64) *TeamAuditLogUpsert {
	u.Add(teamauditlog.FieldResourceID, v)
	return u
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *TeamAuditLogUpsert) ClearResourceID() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldResourceID)
	return u
}

// SetChanges sets the "changes" field.
func (u *TeamAuditLogUpsert) SetChanges(v map[string]interface{}) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldChanges, v)
	return u
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateChanges() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldChanges)
	return u
}

// ClearChanges clears the value of the "changes" field.
func (u *TeamAuditLogUpsert) ClearChanges() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldChanges)
	return u
}

// SetIP sets the "ip" field.
func (u *TeamAuditLogUpsert) SetIP(v string) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateIP() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *TeamAuditLogUpsert) ClearIP() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *TeamAuditLogUpsert) SetUserAgent(v string) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateUserAgent() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TeamAuditLogUpsert) ClearUserAgent() *TeamAuditLogUpsert {
	u.SetNull(teamauditlog.FieldUserAgent)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamAuditLogUpsert) SetCreatedAt(v time.Time) *TeamAuditLogUpsert {
	u.Set(teamauditlog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamAuditLogUpsert) UpdateCreatedAt() *TeamAuditLogUpsert {
	u.SetExcluded(teamauditlog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamAuditLogUpsertOne) UpdateNewValues() *TeamAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamAuditLogUpsertOne) Ignore() *TeamAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamAuditLogUpsertOne) DoNothing() *TeamAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamAuditLogCreate.OnConflict
// documentation for more info.
func (u *TeamAuditLogUpsertOne) Update(set func(*TeamAuditLogUpsert)) *TeamAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamAuditLogUpsertOne) SetTeamID(v int64) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateTeamID() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamAuditLogUpsertOne) SetUserID(v int64) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamAuditLogUpsertOne) AddUserID(v int64) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateUserID() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *TeamAuditLogUpsertOne) ClearUserID() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetAction sets the "action" field.
func (u *TeamAuditLogUpsertOne) SetAction(v string) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateAction() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetOperationType sets the "operation_type" field.
func (u *TeamAuditLogUpsertOne) SetOperationType(v string) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetOperationType(v)
	})
}

// UpdateOperationType sets the "operation_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateOperationType() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateOperationType()
	})
}

// ClearOperationType clears the value of the "operation_type" field.
func (u *TeamAuditLogUpsertOne) ClearOperationType() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearOperationType()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *TeamAuditLogUpsertOne) SetResourceType(v string) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateResourceType() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *TeamAuditLogUpsertOne) SetResourceID(v int64) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *TeamAuditLogUpsertOne) AddResourceID(v int64) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateResourceID() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *TeamAuditLogUpsertOne) ClearResourceID() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearResourceID()
	})
}

// SetChanges sets the "changes" field.
func (u *TeamAuditLogUpsertOne) SetChanges(v map[string]interface{}) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateChanges() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *TeamAuditLogUpsertOne) ClearChanges() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetIP sets the "ip" field.
func (u *TeamAuditLogUpsertOne) SetIP(v string) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateIP() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *TeamAuditLogUpsertOne) ClearIP() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *TeamAuditLogUpsertOne) SetUserAgent(v string) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateUserAgent() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TeamAuditLogUpsertOne) ClearUserAgent() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamAuditLogUpsertOne) SetCreatedAt(v time.Time) *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamAuditLogUpsertOne) UpdateCreatedAt() *TeamAuditLogUpsertOne {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamAuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamAuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamAuditLogCreateBulk is the builder for creating many TeamAuditLog entities in bulk.
type TeamAuditLogCreateBulk struct {
	config
	err      error
	builders []*TeamAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamAuditLog entities in the database.
func (_c *TeamAuditLogCreateBulk) Save(ctx context.Context) ([]*TeamAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamAuditLogCreateBulk) SaveX(ctx context.Context) []*TeamAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamAuditLogUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamAuditLogUpsertBulk {
	_c.conflict = opts
	return &TeamAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamAuditLogCreateBulk) OnConflictColumns(columns ...string) *TeamAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamAuditLogUpsertBulk{
		create: _c,
	}
}

// TeamAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamAuditLog nodes.
type TeamAuditLogUpsertBulk struct {
	create *TeamAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamAuditLogUpsertBulk) UpdateNewValues() *TeamAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamAuditLogUpsertBulk) Ignore() *TeamAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamAuditLogUpsertBulk) DoNothing() *TeamAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *TeamAuditLogUpsertBulk) Update(set func(*TeamAuditLogUpsert)) *TeamAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamAuditLogUpsertBulk) SetTeamID(v int64) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateTeamID() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamAuditLogUpsertBulk) SetUserID(v int64) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamAuditLogUpsertBulk) AddUserID(v int64) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateUserID() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *TeamAuditLogUpsertBulk) ClearUserID() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetAction sets the "action" field.
func (u *TeamAuditLogUpsertBulk) SetAction(v string) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateAction() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetOperationType sets the "operation_type" field.
func (u *TeamAuditLogUpsertBulk) SetOperationType(v string) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetOperationType(v)
	})
}

// UpdateOperationType sets the "operation_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateOperationType() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateOperationType()
	})
}

// ClearOperationType clears the value of the "operation_type" field.
func (u *TeamAuditLogUpsertBulk) ClearOperationType() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearOperationType()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *TeamAuditLogUpsertBulk) SetResourceType(v string) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateResourceType() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *TeamAuditLogUpsertBulk) SetResourceID(v int64) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *TeamAuditLogUpsertBulk) AddResourceID(v int64) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateResourceID() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *TeamAuditLogUpsertBulk) ClearResourceID() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearResourceID()
	})
}

// SetChanges sets the "changes" field.
func (u *TeamAuditLogUpsertBulk) SetChanges(v map[string]interface{}) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateChanges() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *TeamAuditLogUpsertBulk) ClearChanges() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetIP sets the "ip" field.
func (u *TeamAuditLogUpsertBulk) SetIP(v string) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateIP() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *TeamAuditLogUpsertBulk) ClearIP() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *TeamAuditLogUpsertBulk) SetUserAgent(v string) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateUserAgent() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *TeamAuditLogUpsertBulk) ClearUserAgent() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamAuditLogUpsertBulk) SetCreatedAt(v time.Time) *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamAuditLogUpsertBulk) UpdateCreatedAt() *TeamAuditLogUpsertBulk {
	return u.Update(func(s *TeamAuditLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
