// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamauditlog"
)

// TeamAuditLogUpdate is the builder for updating TeamAuditLog entities.
type TeamAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *TeamAuditLogMutation
}

// Where appends a list predicates to the TeamAuditLogUpdate builder.
func (_u *TeamAuditLogUpdate) Where(ps ...predicate.TeamAuditLog) *TeamAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamAuditLogUpdate) SetTeamID(v int64) *TeamAuditLogUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableTeamID(v *int64) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamAuditLogUpdate) SetUserID(v int64) *TeamAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableUserID(v *int64) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TeamAuditLogUpdate) AddUserID(v int64) *TeamAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TeamAuditLogUpdate) ClearUserID() *TeamAuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamAuditLogUpdate) SetAction(v string) *TeamAuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableAction(v *string) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *TeamAuditLogUpdate) SetOperationType(v string) *TeamAuditLogUpdate {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableOperationType(v *string) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// ClearOperationType clears the value of the "operation_type" field.
func (_u *TeamAuditLogUpdate) ClearOperationType() *TeamAuditLogUpdate {
	_u.mutation.ClearOperationType()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TeamAuditLogUpdate) SetResourceType(v string) *TeamAuditLogUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableResourceType(v *string) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TeamAuditLogUpdate) SetResourceID(v int64) *TeamAuditLogUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableResourceID(v *int64) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *TeamAuditLogUpdate) AddResourceID(v int64) *TeamAuditLogUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *TeamAuditLogUpdate) ClearResourceID() *TeamAuditLogUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *TeamAuditLogUpdate) SetChanges(v map[string]interface{}) *TeamAuditLogUpdate {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *TeamAuditLogUpdate) ClearChanges() *TeamAuditLogUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// SetIP sets the "ip" field.
func (_u *TeamAuditLogUpdate) SetIP(v string) *TeamAuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableIP(v *string) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *TeamAuditLogUpdate) ClearIP() *TeamAuditLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TeamAuditLogUpdate) SetUserAgent(v string) *TeamAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableUserAgent(v *string) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *TeamAuditLogUpdate) ClearUserAgent() *TeamAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamAuditLogUpdate) SetCreatedAt(v time.Time) *TeamAuditLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamAuditLogUpdate) SetNillableCreatedAt(v *time.Time) *TeamAuditLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamAuditLogUpdate) SetTeam(v *Team) *TeamAuditLogUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamAuditLogMutation object of the builder.
func (_u *TeamAuditLogUpdate) Mutation() *TeamAuditLogMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamAuditLogUpdate) ClearTeam() *TeamAuditLogUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationType(); ok {
		if err := teamauditlog.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.operation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := teamauditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := teamauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.ip": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAuditLog.team"`)
	}
	return nil
}

func (_u *TeamAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamauditlog.Table, teamauditlog.Columns, sqlgraph.NewFieldSpec(teamauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(teamauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(teamauditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(teamauditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(teamauditlog.FieldOperationType, field.TypeString, value)
	}
	if _u.mutation.OperationTypeCleared() {
		_spec.ClearField(teamauditlog.FieldOperationType, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(teamauditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(teamauditlog.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(teamauditlog.FieldResourceID, field.TypeInt64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(teamauditlog.FieldResourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(teamauditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(teamauditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(teamauditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(teamauditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(teamauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(teamauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamauditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamauditlog.TeamTable,
			Columns: []string{teamauditlog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamauditlog.TeamTable,
			Columns: []string{teamauditlog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamAuditLogUpdateOne is the builder for updating a single TeamAuditLog entity.
type TeamAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamAuditLogMutation
}

// SetTeamID sets the "team_id" field.
func (_u *TeamAuditLogUpdateOne) SetTeamID(v int64) *TeamAuditLogUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableTeamID(v *int64) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamAuditLogUpdateOne) SetUserID(v int64) *TeamAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableUserID(v *int64) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TeamAuditLogUpdateOne) AddUserID(v int64) *TeamAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TeamAuditLogUpdateOne) ClearUserID() *TeamAuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamAuditLogUpdateOne) SetAction(v string) *TeamAuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableAction(v *string) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *TeamAuditLogUpdateOne) SetOperationType(v string) *TeamAuditLogUpdateOne {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableOperationType(v *string) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// ClearOperationType clears the value of the "operation_type" field.
func (_u *TeamAuditLogUpdateOne) ClearOperationType() *TeamAuditLogUpdateOne {
	_u.mutation.ClearOperationType()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TeamAuditLogUpdateOne) SetResourceType(v string) *TeamAuditLogUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableResourceType(v *string) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TeamAuditLogUpdateOne) SetResourceID(v int64) *TeamAuditLogUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableResourceID(v *int64) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *TeamAuditLogUpdateOne) AddResourceID(v int64) *TeamAuditLogUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *TeamAuditLogUpdateOne) ClearResourceID() *TeamAuditLogUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *TeamAuditLogUpdateOne) SetChanges(v map[string]interface{}) *TeamAuditLogUpdateOne {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *TeamAuditLogUpdateOne) ClearChanges() *TeamAuditLogUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// SetIP sets the "ip" field.
func (_u *TeamAuditLogUpdateOne) SetIP(v string) *TeamAuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableIP(v *string) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *TeamAuditLogUpdateOne) ClearIP() *TeamAuditLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TeamAuditLogUpdateOne) SetUserAgent(v string) *TeamAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableUserAgent(v *string) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *TeamAuditLogUpdateOne) ClearUserAgent() *TeamAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamAuditLogUpdateOne) SetCreatedAt(v time.Time) *TeamAuditLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamAuditLogUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamAuditLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamAuditLogUpdateOne) SetTeam(v *Team) *TeamAuditLogUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamAuditLogMutation object of the builder.
func (_u *TeamAuditLogUpdateOne) Mutation() *TeamAuditLogMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamAuditLogUpdateOne) ClearTeam() *TeamAuditLogUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamAuditLogUpdate builder.
func (_u *TeamAuditLogUpdateOne) Where(ps ...predicate.TeamAuditLog) *TeamAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamAuditLogUpdateOne) Select(field string, fields ...string) *TeamAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamAuditLog entity.
func (_u *TeamAuditLogUpdateOne) Save(ctx context.Context) (*TeamAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamAuditLogUpdateOne) SaveX(ctx context.Context) *TeamAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationType(); ok {
		if err := teamauditlog.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.operation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := teamauditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := teamauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.ip": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamAuditLog.team"`)
	}
	return nil
}

func (_u *TeamAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *TeamAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamauditlog.Table, teamauditlog.Columns, sqlgraph.NewFieldSpec(teamauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamauditlog.FieldID)
		for _, f := range fields {
			if !teamauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(teamauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(teamauditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(teamauditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(teamauditlog.FieldOperationType, field.TypeString, value)
	}
	if _u.mutation.OperationTypeCleared() {
		_spec.ClearField(teamauditlog.FieldOperationType, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(teamauditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(teamauditlog.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(teamauditlog.FieldResourceID, field.TypeInt64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(teamauditlog.FieldResourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(teamauditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(teamauditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(teamauditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(teamauditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(teamauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(teamauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamauditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamauditlog.TeamTable,
			Columns: []string{teamauditlog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamauditlog.TeamTable,
			Columns: []string{teamauditlog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
