// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamusagemodeldaily"
)

// TeamUsageModelDailyUpdate is the builder for updating TeamUsageModelDaily entities.
type TeamUsageModelDailyUpdate struct {
	config
	hooks    []Hook
	mutation *TeamUsageModelDailyMutation
}

// Where appends a list predicates to the TeamUsageModelDailyUpdate builder.
func (_u *TeamUsageModelDailyUpdate) Where(ps ...predicate.TeamUsageModelDaily) *TeamUsageModelDailyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUsageModelDailyUpdate) SetUpdatedAt(v time.Time) *TeamUsageModelDailyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamUsageModelDailyUpdate) SetTeamID(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableTeamID(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamUsageModelDailyUpdate) SetDepartmentID(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableDepartmentID(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *TeamUsageModelDailyUpdate) AddDepartmentID(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamUsageModelDailyUpdate) ClearDepartmentID() *TeamUsageModelDailyUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdate) SetConsumerID(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableConsumerID(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdate) AddConsumerID(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddConsumerID(v)
	return _u
}

// ClearConsumerID clears the value of the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdate) ClearConsumerID() *TeamUsageModelDailyUpdate {
	_u.mutation.ClearConsumerID()
	return _u
}

// SetBucketDate sets the "bucket_date" field.
func (_u *TeamUsageModelDailyUpdate) SetBucketDate(v time.Time) *TeamUsageModelDailyUpdate {
	_u.mutation.SetBucketDate(v)
	return _u
}

// SetNillableBucketDate sets the "bucket_date" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableBucketDate(v *time.Time) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetBucketDate(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *TeamUsageModelDailyUpdate) SetModelName(v string) *TeamUsageModelDailyUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableModelName(v *string) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TeamUsageModelDailyUpdate) SetTotalRequests(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableTotalRequests(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TeamUsageModelDailyUpdate) AddTotalRequests(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *TeamUsageModelDailyUpdate) SetInputTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableInputTokens(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *TeamUsageModelDailyUpdate) AddInputTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *TeamUsageModelDailyUpdate) SetOutputTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableOutputTokens(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *TeamUsageModelDailyUpdate) AddOutputTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *TeamUsageModelDailyUpdate) SetCacheCreationTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableCacheCreationTokens(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *TeamUsageModelDailyUpdate) AddCacheCreationTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *TeamUsageModelDailyUpdate) SetCacheReadTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableCacheReadTokens(v *int64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *TeamUsageModelDailyUpdate) AddCacheReadTokens(v int64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *TeamUsageModelDailyUpdate) SetTotalCost(v float64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableTotalCost(v *float64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *TeamUsageModelDailyUpdate) AddTotalCost(v float64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *TeamUsageModelDailyUpdate) SetActualCost(v float64) *TeamUsageModelDailyUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableActualCost(v *float64) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *TeamUsageModelDailyUpdate) AddActualCost(v float64) *TeamUsageModelDailyUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *TeamUsageModelDailyUpdate) SetComputedAt(v time.Time) *TeamUsageModelDailyUpdate {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdate) SetNillableComputedAt(v *time.Time) *TeamUsageModelDailyUpdate {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamUsageModelDailyUpdate) SetTeam(v *Team) *TeamUsageModelDailyUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamUsageModelDailyMutation object of the builder.
func (_u *TeamUsageModelDailyUpdate) Mutation() *TeamUsageModelDailyMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamUsageModelDailyUpdate) ClearTeam() *TeamUsageModelDailyUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUsageModelDailyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUsageModelDailyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUsageModelDailyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUsageModelDailyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUsageModelDailyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamusagemodeldaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUsageModelDailyUpdate) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := teamusagemodeldaily.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "TeamUsageModelDaily.model_name": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageModelDaily.team"`)
	}
	return nil
}

func (_u *TeamUsageModelDailyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamusagemodeldaily.Table, teamusagemodeldaily.Columns, sqlgraph.NewFieldSpec(teamusagemodeldaily.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamusagemodeldaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64, value)
	}
	if _u.mutation.ConsumerIDCleared() {
		_spec.ClearField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BucketDate(); ok {
		_spec.SetField(teamusagemodeldaily.FieldBucketDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(teamusagemodeldaily.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(teamusagemodeldaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(teamusagemodeldaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(teamusagemodeldaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(teamusagemodeldaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(teamusagemodeldaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(teamusagemodeldaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(teamusagemodeldaily.FieldComputedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusagemodeldaily.TeamTable,
			Columns: []string{teamusagemodeldaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusagemodeldaily.TeamTable,
			Columns: []string{teamusagemodeldaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamusagemodeldaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUsageModelDailyUpdateOne is the builder for updating a single TeamUsageModelDaily entity.
type TeamUsageModelDailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamUsageModelDailyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUsageModelDailyUpdateOne) SetUpdatedAt(v time.Time) *TeamUsageModelDailyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamUsageModelDailyUpdateOne) SetTeamID(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableTeamID(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamUsageModelDailyUpdateOne) SetDepartmentID(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableDepartmentID(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *TeamUsageModelDailyUpdateOne) AddDepartmentID(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamUsageModelDailyUpdateOne) ClearDepartmentID() *TeamUsageModelDailyUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdateOne) SetConsumerID(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableConsumerID(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdateOne) AddConsumerID(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddConsumerID(v)
	return _u
}

// ClearConsumerID clears the value of the "consumer_id" field.
func (_u *TeamUsageModelDailyUpdateOne) ClearConsumerID() *TeamUsageModelDailyUpdateOne {
	_u.mutation.ClearConsumerID()
	return _u
}

// SetBucketDate sets the "bucket_date" field.
func (_u *TeamUsageModelDailyUpdateOne) SetBucketDate(v time.Time) *TeamUsageModelDailyUpdateOne {
	_u.mutation.SetBucketDate(v)
	return _u
}

// SetNillableBucketDate sets the "bucket_date" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableBucketDate(v *time.Time) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetBucketDate(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *TeamUsageModelDailyUpdateOne) SetModelName(v string) *TeamUsageModelDailyUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableModelName(v *string) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TeamUsageModelDailyUpdateOne) SetTotalRequests(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableTotalRequests(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TeamUsageModelDailyUpdateOne) AddTotalRequests(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) SetInputTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableInputTokens(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) AddInputTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) SetOutputTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableOutputTokens(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) AddOutputTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) SetCacheCreationTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableCacheCreationTokens(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) AddCacheCreationTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) SetCacheReadTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableCacheReadTokens(v *int64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *TeamUsageModelDailyUpdateOne) AddCacheReadTokens(v int64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *TeamUsageModelDailyUpdateOne) SetTotalCost(v float64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableTotalCost(v *float64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *TeamUsageModelDailyUpdateOne) AddTotalCost(v float64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *TeamUsageModelDailyUpdateOne) SetActualCost(v float64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableActualCost(v *float64) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *TeamUsageModelDailyUpdateOne) AddActualCost(v float64) *TeamUsageModelDailyUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *TeamUsageModelDailyUpdateOne) SetComputedAt(v time.Time) *TeamUsageModelDailyUpdateOne {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *TeamUsageModelDailyUpdateOne) SetNillableComputedAt(v *time.Time) *TeamUsageModelDailyUpdateOne {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamUsageModelDailyUpdateOne) SetTeam(v *Team) *TeamUsageModelDailyUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamUsageModelDailyMutation object of the builder.
func (_u *TeamUsageModelDailyUpdateOne) Mutation() *TeamUsageModelDailyMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamUsageModelDailyUpdateOne) ClearTeam() *TeamUsageModelDailyUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamUsageModelDailyUpdate builder.
func (_u *TeamUsageModelDailyUpdateOne) Where(ps ...predicate.TeamUsageModelDaily) *TeamUsageModelDailyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUsageModelDailyUpdateOne) Select(field string, fields ...string) *TeamUsageModelDailyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamUsageModelDaily entity.
func (_u *TeamUsageModelDailyUpdateOne) Save(ctx context.Context) (*TeamUsageModelDaily, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUsageModelDailyUpdateOne) SaveX(ctx context.Context) *TeamUsageModelDaily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUsageModelDailyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUsageModelDailyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUsageModelDailyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamusagemodeldaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUsageModelDailyUpdateOne) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := teamusagemodeldaily.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "TeamUsageModelDaily.model_name": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageModelDaily.team"`)
	}
	return nil
}

func (_u *TeamUsageModelDailyUpdateOne) sqlSave(ctx context.Context) (_node *TeamUsageModelDaily, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamusagemodeldaily.Table, teamusagemodeldaily.Columns, sqlgraph.NewFieldSpec(teamusagemodeldaily.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamUsageModelDaily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamusagemodeldaily.FieldID)
		for _, f := range fields {
			if !teamusagemodeldaily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamusagemodeldaily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamusagemodeldaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(teamusagemodeldaily.FieldDepartmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64, value)
	}
	if _u.mutation.ConsumerIDCleared() {
		_spec.ClearField(teamusagemodeldaily.FieldConsumerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BucketDate(); ok {
		_spec.SetField(teamusagemodeldaily.FieldBucketDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(teamusagemodeldaily.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(teamusagemodeldaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(teamusagemodeldaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(teamusagemodeldaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(teamusagemodeldaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(teamusagemodeldaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(teamusagemodeldaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(teamusagemodeldaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(teamusagemodeldaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(teamusagemodeldaily.FieldComputedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusagemodeldaily.TeamTable,
			Columns: []string{teamusagemodeldaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusagemodeldaily.TeamTable,
			Columns: []string{teamusagemodeldaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamUsageModelDaily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamusagemodeldaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
