// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamusagemodeldaily"
)

// TeamUsageModelDaily is the model entity for the TeamUsageModelDaily schema.
type TeamUsageModelDaily struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Team ID
	TeamID int64 `json:"team_id,omitempty"`
	// Department ID
	DepartmentID *int64 `json:"department_id,omitempty"`
	// Consumer ID
	ConsumerID *int64 `json:"consumer_id,omitempty"`
	// Aggregation date
	BucketDate time.Time `json:"bucket_date,omitempty"`
	// ModelName holds the value of the "model_name" field.
	ModelName string `json:"model_name,omitempty"`
	// TotalRequests holds the value of the "total_requests" field.
	TotalRequests int64 `json:"total_requests,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int64 `json:"cache_creation_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int64 `json:"cache_read_tokens,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt time.Time `json:"computed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamUsageModelDailyQuery when eager-loading is set.
	Edges        TeamUsageModelDailyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamUsageModelDailyEdges holds the relations/edges for other nodes in the graph.
type TeamUsageModelDailyEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamUsageModelDailyEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamUsageModelDaily) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamusagemodeldaily.FieldTotalCost, teamusagemodeldaily.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case teamusagemodeldaily.FieldID, teamusagemodeldaily.FieldTeamID, teamusagemodeldaily.FieldDepartmentID, teamusagemodeldaily.FieldConsumerID, teamusagemodeldaily.FieldTotalRequests, teamusagemodeldaily.FieldInputTokens, teamusagemodeldaily.FieldOutputTokens, teamusagemodeldaily.FieldCacheCreationTokens, teamusagemodeldaily.FieldCacheReadTokens:
			values[i] = new(sql.NullInt64)
		case teamusagemodeldaily.FieldModelName:
			values[i] = new(sql.NullString)
		case teamusagemodeldaily.FieldCreatedAt, teamusagemodeldaily.FieldUpdatedAt, teamusagemodeldaily.FieldBucketDate, teamusagemodeldaily.FieldComputedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamUsageModelDaily fields.
func (_m *TeamUsageModelDaily) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamusagemodeldaily.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teamusagemodeldaily.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teamusagemodeldaily.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case teamusagemodeldaily.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.Int64
			}
		case teamusagemodeldaily.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = new(int64)
				*_m.DepartmentID = value.Int64
			}
		case teamusagemodeldaily.FieldConsumerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_id", values[i])
			} else if value.Valid {
				_m.ConsumerID = new(int64)
				*_m.ConsumerID = value.Int64
			}
		case teamusagemodeldaily.FieldBucketDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_date", values[i])
			} else if value.Valid {
				_m.BucketDate = value.Time
			}
		case teamusagemodeldaily.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case teamusagemodeldaily.FieldTotalRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_requests", values[i])
			} else if value.Valid {
				_m.TotalRequests = value.Int64
			}
		case teamusagemodeldaily.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case teamusagemodeldaily.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case teamusagemodeldaily.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = value.Int64
			}
		case teamusagemodeldaily.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = value.Int64
			}
		case teamusagemodeldaily.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				_m.TotalCost = value.Float64
			}
		case teamusagemodeldaily.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case teamusagemodeldaily.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamUsageModelDaily.
// This includes values selected through modifiers, order, etc.
func (_m *TeamUsageModelDaily) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamUsageModelDaily entity.
func (_m *TeamUsageModelDaily) QueryTeam() *TeamQuery {
	return NewTeamUsageModelDailyClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this TeamUsageModelDaily.
// Note that you need to call TeamUsageModelDaily.Unwrap() before calling this method if this TeamUsageModelDaily
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamUsageModelDaily) Update() *TeamUsageModelDailyUpdateOne {
	return NewTeamUsageModelDailyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamUsageModelDaily entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamUsageModelDaily) Unwrap() *TeamUsageModelDaily {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamUsageModelDaily is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamUsageModelDaily) String() string {
	var builder strings.Builder
	builder.WriteString("TeamUsageModelDaily(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	if v := _m.DepartmentID; v != nil {
		builder.WriteString("department_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConsumerID; v != nil {
		builder.WriteString("consumer_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("bucket_date=")
	builder.WriteString(_m.BucketDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	builder.WriteString("total_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRequests))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamUsageModelDailies is a parsable slice of TeamUsageModelDaily.
type TeamUsageModelDailies []*TeamUsageModelDaily
