// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/consumer"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamMemberUpdate is the builder for updating TeamMember entities.
type TeamMemberUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMemberMutation
}

// Where appends a list predicates to the TeamMemberUpdate builder.
func (_u *TeamMemberUpdate) Where(ps ...predicate.TeamMember) *TeamMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMemberUpdate) SetUpdatedAt(v time.Time) *TeamMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMemberUpdate) SetTeamID(v int64) *TeamMemberUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableTeamID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamMemberUpdate) SetUserID(v int64) *TeamMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableUserID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TeamMemberUpdate) SetRole(v string) *TeamMemberUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableRole(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMemberUpdate) SetStatus(v string) *TeamMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableStatus(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TeamMemberUpdate) SetDisplayName(v string) *TeamMemberUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableDisplayName(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *TeamMemberUpdate) ClearDisplayName() *TeamMemberUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamMemberUpdate) SetDepartmentID(v int64) *TeamMemberUpdate {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableDepartmentID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamMemberUpdate) ClearDepartmentID() *TeamMemberUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamMemberUpdate) SetConsumerID(v int64) *TeamMemberUpdate {
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableConsumerID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// ClearConsumerID clears the value of the "consumer_id" field.
func (_u *TeamMemberUpdate) ClearConsumerID() *TeamMemberUpdate {
	_u.mutation.ClearConsumerID()
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TeamMemberUpdate) SetJoinedAt(v time.Time) *TeamMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableJoinedAt(v *time.Time) *TeamMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMemberUpdate) SetTeam(v *Team) *TeamMemberUpdate {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamMemberUpdate) SetUser(v *User) *TeamMemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *TeamMemberUpdate) SetDepartment(v *Department) *TeamMemberUpdate {
	return _u.SetDepartmentID(v.ID)
}

// SetConsumer sets the "consumer" edge to the Consumer entity.
func (_u *TeamMemberUpdate) SetConsumer(v *Consumer) *TeamMemberUpdate {
	return _u.SetConsumerID(v.ID)
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_u *TeamMemberUpdate) Mutation() *TeamMemberMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMemberUpdate) ClearTeam() *TeamMemberUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamMemberUpdate) ClearUser() *TeamMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *TeamMemberUpdate) ClearDepartment() *TeamMemberUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearConsumer clears the "consumer" edge to the Consumer entity.
func (_u *TeamMemberUpdate) ClearConsumer() *TeamMemberUpdate {
	_u.mutation.ClearConsumer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMemberUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := teammember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := teammember.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "TeamMember.display_name": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMember.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMember.user"`)
	}
	return nil
}

func (_u *TeamMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammember.Table, teammember.Columns, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(teammember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(teammember.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(teammember.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(teammember.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.TeamTable,
			Columns: []string{teammember.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.TeamTable,
			Columns: []string{teammember.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.UserTable,
			Columns: []string{teammember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.UserTable,
			Columns: []string{teammember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.DepartmentTable,
			Columns: []string{teammember.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.DepartmentTable,
			Columns: []string{teammember.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.ConsumerTable,
			Columns: []string{teammember.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.ConsumerTable,
			Columns: []string{teammember.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamMemberUpdateOne is the builder for updating a single TeamMember entity.
type TeamMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMemberUpdateOne) SetUpdatedAt(v time.Time) *TeamMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMemberUpdateOne) SetTeamID(v int64) *TeamMemberUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableTeamID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamMemberUpdateOne) SetUserID(v int64) *TeamMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableUserID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TeamMemberUpdateOne) SetRole(v string) *TeamMemberUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableRole(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMemberUpdateOne) SetStatus(v string) *TeamMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableStatus(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TeamMemberUpdateOne) SetDisplayName(v string) *TeamMemberUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableDisplayName(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *TeamMemberUpdateOne) ClearDisplayName() *TeamMemberUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamMemberUpdateOne) SetDepartmentID(v int64) *TeamMemberUpdateOne {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableDepartmentID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamMemberUpdateOne) ClearDepartmentID() *TeamMemberUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamMemberUpdateOne) SetConsumerID(v int64) *TeamMemberUpdateOne {
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableConsumerID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// ClearConsumerID clears the value of the "consumer_id" field.
func (_u *TeamMemberUpdateOne) ClearConsumerID() *TeamMemberUpdateOne {
	_u.mutation.ClearConsumerID()
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TeamMemberUpdateOne) SetJoinedAt(v time.Time) *TeamMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMemberUpdateOne) SetTeam(v *Team) *TeamMemberUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamMemberUpdateOne) SetUser(v *User) *TeamMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *TeamMemberUpdateOne) SetDepartment(v *Department) *TeamMemberUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// SetConsumer sets the "consumer" edge to the Consumer entity.
func (_u *TeamMemberUpdateOne) SetConsumer(v *Consumer) *TeamMemberUpdateOne {
	return _u.SetConsumerID(v.ID)
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_u *TeamMemberUpdateOne) Mutation() *TeamMemberMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMemberUpdateOne) ClearTeam() *TeamMemberUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamMemberUpdateOne) ClearUser() *TeamMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *TeamMemberUpdateOne) ClearDepartment() *TeamMemberUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearConsumer clears the "consumer" edge to the Consumer entity.
func (_u *TeamMemberUpdateOne) ClearConsumer() *TeamMemberUpdateOne {
	_u.mutation.ClearConsumer()
	return _u
}

// Where appends a list predicates to the TeamMemberUpdate builder.
func (_u *TeamMemberUpdateOne) Where(ps ...predicate.TeamMember) *TeamMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamMemberUpdateOne) Select(field string, fields ...string) *TeamMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamMember entity.
func (_u *TeamMemberUpdateOne) Save(ctx context.Context) (*TeamMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMemberUpdateOne) SaveX(ctx context.Context) *TeamMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMemberUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := teammember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := teammember.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "TeamMember.display_name": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMember.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMember.user"`)
	}
	return nil
}

func (_u *TeamMemberUpdateOne) sqlSave(ctx context.Context) (_node *TeamMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammember.Table, teammember.Columns, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teammember.FieldID)
		for _, f := range fields {
			if !teammember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teammember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(teammember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(teammember.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(teammember.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(teammember.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.TeamTable,
			Columns: []string{teammember.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.TeamTable,
			Columns: []string{teammember.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.UserTable,
			Columns: []string{teammember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.UserTable,
			Columns: []string{teammember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.DepartmentTable,
			Columns: []string{teammember.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.DepartmentTable,
			Columns: []string{teammember.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.ConsumerTable,
			Columns: []string{teammember.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammember.ConsumerTable,
			Columns: []string{teammember.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
