// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/consumer"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamusageconsumerdaily"
)

// TeamUsageConsumerDailyUpdate is the builder for updating TeamUsageConsumerDaily entities.
type TeamUsageConsumerDailyUpdate struct {
	config
	hooks    []Hook
	mutation *TeamUsageConsumerDailyMutation
}

// Where appends a list predicates to the TeamUsageConsumerDailyUpdate builder.
func (_u *TeamUsageConsumerDailyUpdate) Where(ps ...predicate.TeamUsageConsumerDaily) *TeamUsageConsumerDailyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUsageConsumerDailyUpdate) SetUpdatedAt(v time.Time) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamUsageConsumerDailyUpdate) SetTeamID(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableTeamID(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamUsageConsumerDailyUpdate) SetConsumerID(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableConsumerID(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// SetConsumerName sets the "consumer_name" field.
func (_u *TeamUsageConsumerDailyUpdate) SetConsumerName(v string) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetConsumerName(v)
	return _u
}

// SetNillableConsumerName sets the "consumer_name" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableConsumerName(v *string) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetConsumerName(*v)
	}
	return _u
}

// ClearConsumerName clears the value of the "consumer_name" field.
func (_u *TeamUsageConsumerDailyUpdate) ClearConsumerName() *TeamUsageConsumerDailyUpdate {
	_u.mutation.ClearConsumerName()
	return _u
}

// SetConsumerType sets the "consumer_type" field.
func (_u *TeamUsageConsumerDailyUpdate) SetConsumerType(v string) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetConsumerType(v)
	return _u
}

// SetNillableConsumerType sets the "consumer_type" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableConsumerType(v *string) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetConsumerType(*v)
	}
	return _u
}

// ClearConsumerType clears the value of the "consumer_type" field.
func (_u *TeamUsageConsumerDailyUpdate) ClearConsumerType() *TeamUsageConsumerDailyUpdate {
	_u.mutation.ClearConsumerType()
	return _u
}

// SetBucketDate sets the "bucket_date" field.
func (_u *TeamUsageConsumerDailyUpdate) SetBucketDate(v time.Time) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetBucketDate(v)
	return _u
}

// SetNillableBucketDate sets the "bucket_date" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableBucketDate(v *time.Time) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetBucketDate(*v)
	}
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TeamUsageConsumerDailyUpdate) SetTotalRequests(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableTotalRequests(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TeamUsageConsumerDailyUpdate) AddTotalRequests(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) SetInputTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableInputTokens(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) AddInputTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) SetOutputTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableOutputTokens(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) AddOutputTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) SetCacheCreationTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableCacheCreationTokens(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) AddCacheCreationTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) SetCacheReadTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableCacheReadTokens(v *int64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *TeamUsageConsumerDailyUpdate) AddCacheReadTokens(v int64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *TeamUsageConsumerDailyUpdate) SetTotalCost(v float64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableTotalCost(v *float64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *TeamUsageConsumerDailyUpdate) AddTotalCost(v float64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *TeamUsageConsumerDailyUpdate) SetActualCost(v float64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableActualCost(v *float64) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *TeamUsageConsumerDailyUpdate) AddActualCost(v float64) *TeamUsageConsumerDailyUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *TeamUsageConsumerDailyUpdate) SetComputedAt(v time.Time) *TeamUsageConsumerDailyUpdate {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdate) SetNillableComputedAt(v *time.Time) *TeamUsageConsumerDailyUpdate {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamUsageConsumerDailyUpdate) SetTeam(v *Team) *TeamUsageConsumerDailyUpdate {
	return _u.SetTeamID(v.ID)
}

// SetConsumer sets the "consumer" edge to the Consumer entity.
func (_u *TeamUsageConsumerDailyUpdate) SetConsumer(v *Consumer) *TeamUsageConsumerDailyUpdate {
	return _u.SetConsumerID(v.ID)
}

// Mutation returns the TeamUsageConsumerDailyMutation object of the builder.
func (_u *TeamUsageConsumerDailyUpdate) Mutation() *TeamUsageConsumerDailyMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamUsageConsumerDailyUpdate) ClearTeam() *TeamUsageConsumerDailyUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearConsumer clears the "consumer" edge to the Consumer entity.
func (_u *TeamUsageConsumerDailyUpdate) ClearConsumer() *TeamUsageConsumerDailyUpdate {
	_u.mutation.ClearConsumer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUsageConsumerDailyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUsageConsumerDailyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUsageConsumerDailyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUsageConsumerDailyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUsageConsumerDailyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamusageconsumerdaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUsageConsumerDailyUpdate) check() error {
	if v, ok := _u.mutation.ConsumerName(); ok {
		if err := teamusageconsumerdaily.ConsumerNameValidator(v); err != nil {
			return &ValidationError{Name: "consumer_name", err: fmt.Errorf(`ent: validator failed for field "TeamUsageConsumerDaily.consumer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumerType(); ok {
		if err := teamusageconsumerdaily.ConsumerTypeValidator(v); err != nil {
			return &ValidationError{Name: "consumer_type", err: fmt.Errorf(`ent: validator failed for field "TeamUsageConsumerDaily.consumer_type": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageConsumerDaily.team"`)
	}
	if _u.mutation.ConsumerCleared() && len(_u.mutation.ConsumerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageConsumerDaily.consumer"`)
	}
	return nil
}

func (_u *TeamUsageConsumerDailyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamusageconsumerdaily.Table, teamusageconsumerdaily.Columns, sqlgraph.NewFieldSpec(teamusageconsumerdaily.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumerName(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldConsumerName, field.TypeString, value)
	}
	if _u.mutation.ConsumerNameCleared() {
		_spec.ClearField(teamusageconsumerdaily.FieldConsumerName, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumerType(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldConsumerType, field.TypeString, value)
	}
	if _u.mutation.ConsumerTypeCleared() {
		_spec.ClearField(teamusageconsumerdaily.FieldConsumerType, field.TypeString)
	}
	if value, ok := _u.mutation.BucketDate(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldBucketDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldComputedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.TeamTable,
			Columns: []string{teamusageconsumerdaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.TeamTable,
			Columns: []string{teamusageconsumerdaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.ConsumerTable,
			Columns: []string{teamusageconsumerdaily.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.ConsumerTable,
			Columns: []string{teamusageconsumerdaily.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamusageconsumerdaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUsageConsumerDailyUpdateOne is the builder for updating a single TeamUsageConsumerDaily entity.
type TeamUsageConsumerDailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamUsageConsumerDailyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetUpdatedAt(v time.Time) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetTeamID(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableTeamID(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetConsumerID(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableConsumerID(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// SetConsumerName sets the "consumer_name" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetConsumerName(v string) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetConsumerName(v)
	return _u
}

// SetNillableConsumerName sets the "consumer_name" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableConsumerName(v *string) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetConsumerName(*v)
	}
	return _u
}

// ClearConsumerName clears the value of the "consumer_name" field.
func (_u *TeamUsageConsumerDailyUpdateOne) ClearConsumerName() *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ClearConsumerName()
	return _u
}

// SetConsumerType sets the "consumer_type" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetConsumerType(v string) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetConsumerType(v)
	return _u
}

// SetNillableConsumerType sets the "consumer_type" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableConsumerType(v *string) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetConsumerType(*v)
	}
	return _u
}

// ClearConsumerType clears the value of the "consumer_type" field.
func (_u *TeamUsageConsumerDailyUpdateOne) ClearConsumerType() *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ClearConsumerType()
	return _u
}

// SetBucketDate sets the "bucket_date" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetBucketDate(v time.Time) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetBucketDate(v)
	return _u
}

// SetNillableBucketDate sets the "bucket_date" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableBucketDate(v *time.Time) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetBucketDate(*v)
	}
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetTotalRequests(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableTotalRequests(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddTotalRequests(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetInputTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableInputTokens(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddInputTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetOutputTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableOutputTokens(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddOutputTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetCacheCreationTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableCacheCreationTokens(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddCacheCreationTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetCacheReadTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableCacheReadTokens(v *int64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddCacheReadTokens(v int64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetTotalCost(v float64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableTotalCost(v *float64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddTotalCost(v float64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetActualCost(v float64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableActualCost(v *float64) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *TeamUsageConsumerDailyUpdateOne) AddActualCost(v float64) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *TeamUsageConsumerDailyUpdateOne) SetComputedAt(v time.Time) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *TeamUsageConsumerDailyUpdateOne) SetNillableComputedAt(v *time.Time) *TeamUsageConsumerDailyUpdateOne {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamUsageConsumerDailyUpdateOne) SetTeam(v *Team) *TeamUsageConsumerDailyUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetConsumer sets the "consumer" edge to the Consumer entity.
func (_u *TeamUsageConsumerDailyUpdateOne) SetConsumer(v *Consumer) *TeamUsageConsumerDailyUpdateOne {
	return _u.SetConsumerID(v.ID)
}

// Mutation returns the TeamUsageConsumerDailyMutation object of the builder.
func (_u *TeamUsageConsumerDailyUpdateOne) Mutation() *TeamUsageConsumerDailyMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamUsageConsumerDailyUpdateOne) ClearTeam() *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearConsumer clears the "consumer" edge to the Consumer entity.
func (_u *TeamUsageConsumerDailyUpdateOne) ClearConsumer() *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.ClearConsumer()
	return _u
}

// Where appends a list predicates to the TeamUsageConsumerDailyUpdate builder.
func (_u *TeamUsageConsumerDailyUpdateOne) Where(ps ...predicate.TeamUsageConsumerDaily) *TeamUsageConsumerDailyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUsageConsumerDailyUpdateOne) Select(field string, fields ...string) *TeamUsageConsumerDailyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamUsageConsumerDaily entity.
func (_u *TeamUsageConsumerDailyUpdateOne) Save(ctx context.Context) (*TeamUsageConsumerDaily, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUsageConsumerDailyUpdateOne) SaveX(ctx context.Context) *TeamUsageConsumerDaily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUsageConsumerDailyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUsageConsumerDailyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUsageConsumerDailyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamusageconsumerdaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUsageConsumerDailyUpdateOne) check() error {
	if v, ok := _u.mutation.ConsumerName(); ok {
		if err := teamusageconsumerdaily.ConsumerNameValidator(v); err != nil {
			return &ValidationError{Name: "consumer_name", err: fmt.Errorf(`ent: validator failed for field "TeamUsageConsumerDaily.consumer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumerType(); ok {
		if err := teamusageconsumerdaily.ConsumerTypeValidator(v); err != nil {
			return &ValidationError{Name: "consumer_type", err: fmt.Errorf(`ent: validator failed for field "TeamUsageConsumerDaily.consumer_type": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageConsumerDaily.team"`)
	}
	if _u.mutation.ConsumerCleared() && len(_u.mutation.ConsumerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamUsageConsumerDaily.consumer"`)
	}
	return nil
}

func (_u *TeamUsageConsumerDailyUpdateOne) sqlSave(ctx context.Context) (_node *TeamUsageConsumerDaily, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamusageconsumerdaily.Table, teamusageconsumerdaily.Columns, sqlgraph.NewFieldSpec(teamusageconsumerdaily.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamUsageConsumerDaily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamusageconsumerdaily.FieldID)
		for _, f := range fields {
			if !teamusageconsumerdaily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamusageconsumerdaily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumerName(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldConsumerName, field.TypeString, value)
	}
	if _u.mutation.ConsumerNameCleared() {
		_spec.ClearField(teamusageconsumerdaily.FieldConsumerName, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumerType(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldConsumerType, field.TypeString, value)
	}
	if _u.mutation.ConsumerTypeCleared() {
		_spec.ClearField(teamusageconsumerdaily.FieldConsumerType, field.TypeString)
	}
	if value, ok := _u.mutation.BucketDate(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldBucketDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(teamusageconsumerdaily.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(teamusageconsumerdaily.FieldComputedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.TeamTable,
			Columns: []string{teamusageconsumerdaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.TeamTable,
			Columns: []string{teamusageconsumerdaily.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.ConsumerTable,
			Columns: []string{teamusageconsumerdaily.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamusageconsumerdaily.ConsumerTable,
			Columns: []string{teamusageconsumerdaily.ConsumerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consumer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamUsageConsumerDaily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamusageconsumerdaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
