// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTask is the model entity for the VideoTask schema.
type VideoTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 对用户暴露的唯一任务 ID，如 vid_xxx
	LocalID string `json:"local_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// 用户请求的统一模型名，如 seedance-2.5
	PublicModel string `json:"public_model,omitempty"`
	// model_mapping 翻译后上游实际模型名
	UpstreamModel string `json:"upstream_model,omitempty"`
	// 实际使用的上游 channel (Account) ID
	AccountID int64 `json:"account_id,omitempty"`
	// 上游返回的任务 ID
	UpstreamTaskID string `json:"upstream_task_id,omitempty"`
	// processing / succeeded / failed / cancelled
	Status string `json:"status,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// DurationSec holds the value of the "duration_sec" field.
	DurationSec int `json:"duration_sec,omitempty"`
	// VideoURL holds the value of the "video_url" field.
	VideoURL string `json:"video_url,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL string `json:"thumbnail_url,omitempty"`
	// 原始请求快照，便于排障
	RequestBody map[string]interface{} `json:"request_body,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CostUsd holds the value of the "cost_usd" field.
	CostUsd float64 `json:"cost_usd,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videotask.FieldRequestBody:
			values[i] = new([]byte)
		case videotask.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case videotask.FieldID, videotask.FieldUserID, videotask.FieldAPIKeyID, videotask.FieldAccountID, videotask.FieldDurationSec:
			values[i] = new(sql.NullInt64)
		case videotask.FieldLocalID, videotask.FieldPublicModel, videotask.FieldUpstreamModel, videotask.FieldUpstreamTaskID, videotask.FieldStatus, videotask.FieldResolution, videotask.FieldVideoURL, videotask.FieldThumbnailURL, videotask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case videotask.FieldCreatedAt, videotask.FieldUpdatedAt, videotask.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoTask fields.
func (_m *VideoTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videotask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videotask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videotask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videotask.FieldLocalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_id", values[i])
			} else if value.Valid {
				_m.LocalID = value.String
			}
		case videotask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case videotask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case videotask.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case videotask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case videotask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case videotask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = value.String
			}
		case videotask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videotask.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case videotask.FieldDurationSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_sec", values[i])
			} else if value.Valid {
				_m.DurationSec = int(value.Int64)
			}
		case videotask.FieldVideoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_url", values[i])
			} else if value.Valid {
				_m.VideoURL = value.String
			}
		case videotask.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = value.String
			}
		case videotask.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestBody); err != nil {
					return fmt.Errorf("unmarshal field request_body: %w", err)
				}
			}
		case videotask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case videotask.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case videotask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoTask.
// This includes values selected through modifiers, order, etc.
func (_m *VideoTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoTask.
// Note that you need to call VideoTask.Unwrap() before calling this method if this VideoTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoTask) Update() *VideoTaskUpdateOne {
	return NewVideoTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoTask) Unwrap() *VideoTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoTask) String() string {
	var builder strings.Builder
	builder.WriteString("VideoTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("local_id=")
	builder.WriteString(_m.LocalID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("upstream_task_id=")
	builder.WriteString(_m.UpstreamTaskID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("duration_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSec))
	builder.WriteString(", ")
	builder.WriteString("video_url=")
	builder.WriteString(_m.VideoURL)
	builder.WriteString(", ")
	builder.WriteString("thumbnail_url=")
	builder.WriteString(_m.ThumbnailURL)
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VideoTasks is a parsable slice of VideoTask.
type VideoTasks []*VideoTask
