// Code generated by ent, DO NOT EDIT.

package teamusageteamdaily

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTeamID, v))
}

// BucketDate applies equality check predicate on the "bucket_date" field. It's identical to BucketDateEQ.
func BucketDate(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldBucketDate, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTotalRequests, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCacheReadTokens, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldActualCost, v))
}

// ComputedAt applies equality check predicate on the "computed_at" field. It's identical to ComputedAtEQ.
func ComputedAt(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldComputedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldTeamID, vs...))
}

// BucketDateEQ applies the EQ predicate on the "bucket_date" field.
func BucketDateEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldBucketDate, v))
}

// BucketDateNEQ applies the NEQ predicate on the "bucket_date" field.
func BucketDateNEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldBucketDate, v))
}

// BucketDateIn applies the In predicate on the "bucket_date" field.
func BucketDateIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldBucketDate, vs...))
}

// BucketDateNotIn applies the NotIn predicate on the "bucket_date" field.
func BucketDateNotIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldBucketDate, vs...))
}

// BucketDateGT applies the GT predicate on the "bucket_date" field.
func BucketDateGT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldBucketDate, v))
}

// BucketDateGTE applies the GTE predicate on the "bucket_date" field.
func BucketDateGTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldBucketDate, v))
}

// BucketDateLT applies the LT predicate on the "bucket_date" field.
func BucketDateLT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldBucketDate, v))
}

// BucketDateLTE applies the LTE predicate on the "bucket_date" field.
func BucketDateLTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldBucketDate, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldTotalRequests, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldCacheReadTokens, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldActualCost, v))
}

// ComputedAtEQ applies the EQ predicate on the "computed_at" field.
func ComputedAtEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldEQ(FieldComputedAt, v))
}

// ComputedAtNEQ applies the NEQ predicate on the "computed_at" field.
func ComputedAtNEQ(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNEQ(FieldComputedAt, v))
}

// ComputedAtIn applies the In predicate on the "computed_at" field.
func ComputedAtIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldIn(FieldComputedAt, vs...))
}

// ComputedAtNotIn applies the NotIn predicate on the "computed_at" field.
func ComputedAtNotIn(vs ...time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldNotIn(FieldComputedAt, vs...))
}

// ComputedAtGT applies the GT predicate on the "computed_at" field.
func ComputedAtGT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGT(FieldComputedAt, v))
}

// ComputedAtGTE applies the GTE predicate on the "computed_at" field.
func ComputedAtGTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldGTE(FieldComputedAt, v))
}

// ComputedAtLT applies the LT predicate on the "computed_at" field.
func ComputedAtLT(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLT(FieldComputedAt, v))
}

// ComputedAtLTE applies the LTE predicate on the "computed_at" field.
func ComputedAtLTE(v time.Time) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.FieldLTE(FieldComputedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamUsageTeamDaily) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamUsageTeamDaily) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamUsageTeamDaily) predicate.TeamUsageTeamDaily {
	return predicate.TeamUsageTeamDaily(sql.NotPredicates(p))
}
