// Code generated by ent, DO NOT EDIT.

package teamusagedeptdaily

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTeamID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentName applies equality check predicate on the "department_name" field. It's identical to DepartmentNameEQ.
func DepartmentName(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldDepartmentName, v))
}

// CostCenterCode applies equality check predicate on the "cost_center_code" field. It's identical to CostCenterCodeEQ.
func CostCenterCode(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCostCenterCode, v))
}

// BucketDate applies equality check predicate on the "bucket_date" field. It's identical to BucketDateEQ.
func BucketDate(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldBucketDate, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTotalRequests, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCacheReadTokens, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldActualCost, v))
}

// ComputedAt applies equality check predicate on the "computed_at" field. It's identical to ComputedAtEQ.
func ComputedAt(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldComputedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldTeamID, vs...))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentNameEQ applies the EQ predicate on the "department_name" field.
func DepartmentNameEQ(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldDepartmentName, v))
}

// DepartmentNameNEQ applies the NEQ predicate on the "department_name" field.
func DepartmentNameNEQ(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldDepartmentName, v))
}

// DepartmentNameIn applies the In predicate on the "department_name" field.
func DepartmentNameIn(vs ...string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldDepartmentName, vs...))
}

// DepartmentNameNotIn applies the NotIn predicate on the "department_name" field.
func DepartmentNameNotIn(vs ...string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldDepartmentName, vs...))
}

// DepartmentNameGT applies the GT predicate on the "department_name" field.
func DepartmentNameGT(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldDepartmentName, v))
}

// DepartmentNameGTE applies the GTE predicate on the "department_name" field.
func DepartmentNameGTE(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldDepartmentName, v))
}

// DepartmentNameLT applies the LT predicate on the "department_name" field.
func DepartmentNameLT(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldDepartmentName, v))
}

// DepartmentNameLTE applies the LTE predicate on the "department_name" field.
func DepartmentNameLTE(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldDepartmentName, v))
}

// DepartmentNameContains applies the Contains predicate on the "department_name" field.
func DepartmentNameContains(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldContains(FieldDepartmentName, v))
}

// DepartmentNameHasPrefix applies the HasPrefix predicate on the "department_name" field.
func DepartmentNameHasPrefix(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldHasPrefix(FieldDepartmentName, v))
}

// DepartmentNameHasSuffix applies the HasSuffix predicate on the "department_name" field.
func DepartmentNameHasSuffix(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldHasSuffix(FieldDepartmentName, v))
}

// DepartmentNameIsNil applies the IsNil predicate on the "department_name" field.
func DepartmentNameIsNil() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIsNull(FieldDepartmentName))
}

// DepartmentNameNotNil applies the NotNil predicate on the "department_name" field.
func DepartmentNameNotNil() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotNull(FieldDepartmentName))
}

// DepartmentNameEqualFold applies the EqualFold predicate on the "department_name" field.
func DepartmentNameEqualFold(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEqualFold(FieldDepartmentName, v))
}

// DepartmentNameContainsFold applies the ContainsFold predicate on the "department_name" field.
func DepartmentNameContainsFold(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldContainsFold(FieldDepartmentName, v))
}

// CostCenterCodeEQ applies the EQ predicate on the "cost_center_code" field.
func CostCenterCodeEQ(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCostCenterCode, v))
}

// CostCenterCodeNEQ applies the NEQ predicate on the "cost_center_code" field.
func CostCenterCodeNEQ(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldCostCenterCode, v))
}

// CostCenterCodeIn applies the In predicate on the "cost_center_code" field.
func CostCenterCodeIn(vs ...string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldCostCenterCode, vs...))
}

// CostCenterCodeNotIn applies the NotIn predicate on the "cost_center_code" field.
func CostCenterCodeNotIn(vs ...string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldCostCenterCode, vs...))
}

// CostCenterCodeGT applies the GT predicate on the "cost_center_code" field.
func CostCenterCodeGT(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldCostCenterCode, v))
}

// CostCenterCodeGTE applies the GTE predicate on the "cost_center_code" field.
func CostCenterCodeGTE(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldCostCenterCode, v))
}

// CostCenterCodeLT applies the LT predicate on the "cost_center_code" field.
func CostCenterCodeLT(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldCostCenterCode, v))
}

// CostCenterCodeLTE applies the LTE predicate on the "cost_center_code" field.
func CostCenterCodeLTE(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldCostCenterCode, v))
}

// CostCenterCodeContains applies the Contains predicate on the "cost_center_code" field.
func CostCenterCodeContains(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldContains(FieldCostCenterCode, v))
}

// CostCenterCodeHasPrefix applies the HasPrefix predicate on the "cost_center_code" field.
func CostCenterCodeHasPrefix(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldHasPrefix(FieldCostCenterCode, v))
}

// CostCenterCodeHasSuffix applies the HasSuffix predicate on the "cost_center_code" field.
func CostCenterCodeHasSuffix(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldHasSuffix(FieldCostCenterCode, v))
}

// CostCenterCodeIsNil applies the IsNil predicate on the "cost_center_code" field.
func CostCenterCodeIsNil() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIsNull(FieldCostCenterCode))
}

// CostCenterCodeNotNil applies the NotNil predicate on the "cost_center_code" field.
func CostCenterCodeNotNil() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotNull(FieldCostCenterCode))
}

// CostCenterCodeEqualFold applies the EqualFold predicate on the "cost_center_code" field.
func CostCenterCodeEqualFold(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEqualFold(FieldCostCenterCode, v))
}

// CostCenterCodeContainsFold applies the ContainsFold predicate on the "cost_center_code" field.
func CostCenterCodeContainsFold(v string) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldContainsFold(FieldCostCenterCode, v))
}

// BucketDateEQ applies the EQ predicate on the "bucket_date" field.
func BucketDateEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldBucketDate, v))
}

// BucketDateNEQ applies the NEQ predicate on the "bucket_date" field.
func BucketDateNEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldBucketDate, v))
}

// BucketDateIn applies the In predicate on the "bucket_date" field.
func BucketDateIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldBucketDate, vs...))
}

// BucketDateNotIn applies the NotIn predicate on the "bucket_date" field.
func BucketDateNotIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldBucketDate, vs...))
}

// BucketDateGT applies the GT predicate on the "bucket_date" field.
func BucketDateGT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldBucketDate, v))
}

// BucketDateGTE applies the GTE predicate on the "bucket_date" field.
func BucketDateGTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldBucketDate, v))
}

// BucketDateLT applies the LT predicate on the "bucket_date" field.
func BucketDateLT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldBucketDate, v))
}

// BucketDateLTE applies the LTE predicate on the "bucket_date" field.
func BucketDateLTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldBucketDate, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldTotalRequests, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldCacheReadTokens, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldActualCost, v))
}

// ComputedAtEQ applies the EQ predicate on the "computed_at" field.
func ComputedAtEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldEQ(FieldComputedAt, v))
}

// ComputedAtNEQ applies the NEQ predicate on the "computed_at" field.
func ComputedAtNEQ(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNEQ(FieldComputedAt, v))
}

// ComputedAtIn applies the In predicate on the "computed_at" field.
func ComputedAtIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldIn(FieldComputedAt, vs...))
}

// ComputedAtNotIn applies the NotIn predicate on the "computed_at" field.
func ComputedAtNotIn(vs ...time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldNotIn(FieldComputedAt, vs...))
}

// ComputedAtGT applies the GT predicate on the "computed_at" field.
func ComputedAtGT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGT(FieldComputedAt, v))
}

// ComputedAtGTE applies the GTE predicate on the "computed_at" field.
func ComputedAtGTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldGTE(FieldComputedAt, v))
}

// ComputedAtLT applies the LT predicate on the "computed_at" field.
func ComputedAtLT(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLT(FieldComputedAt, v))
}

// ComputedAtLTE applies the LTE predicate on the "computed_at" field.
func ComputedAtLTE(v time.Time) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.FieldLTE(FieldComputedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(func(s *sql.Selector) {
		step := newDepartmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamUsageDeptDaily) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamUsageDeptDaily) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamUsageDeptDaily) predicate.TeamUsageDeptDaily {
	return predicate.TeamUsageDeptDaily(sql.NotPredicates(p))
}
